### ISSUE TITLE
Timeout-parameter for lumi.sensor_motion.aq2

### ISSUE THREAD

**Issue by baustoff** [ioBroker/ioBroker.mihome#27] opened 2018-08-17 09:59 UTC
Hello,

is it possible to add a timeout-parameter (value=seconds) for the AQARA Motion sensor (lumi.sensor_motion.aq2)?

I want my sensor to recognize motions and turn the lights on in the bathroom for instance. It should immeditaly new motions turn off the lights again if there is no motion anymore, but keep the lights on if new motions have been recognized

I'm experiencing the following issue:  By default the sensor recognizes the first motion and remains in motion-status=true for 60 secs exactly.  This means that the sensor is not able to recognize new motions within the 60 seconds.

With the mentioned timeout-valueI would like to set the 60 secs to 3 secs for instance. So the sensor would be able to recognize motions every 3 secs after first recognition.

Thank you in advance.

**Comment by GermanBluefox** [comment] 2018-08-17 21:28
I think, that the problem is: the sensor_motion just does not send motion event earlier than 60 seconds.
It is no matter how fast we on the IoB side will think, that motion is over, but you cannot change the interval IN SENSOR from 60 seconds to 3 seconds

**Comment by Ilovegym66** [comment] 2018-09-07 06:52
I've set the object is-motion writable, and set it after 30 sec to false. In the most situations it's now better. In my scripts I've set the delay for minimum of 2minutes, this works fine.
The "Problem" is in the sensor software, it's energy saving issue, I'm think.

**Comment by baustoff** [comment] 2018-09-07 08:02
Actually I think both of you are right. After setting the is-motion-value to false after 10 sec, I recognized a huge battery-drain from nearly 100% to 65% within 2-3 hours. And this fact confirms your assumption, which would mean there will be no way to handle my mention scenario due to sensor-software limitation unfortunately.

**Comment by GermanBluefox** [comment] 2018-09-07 09:07
So I close it.

**Closed by GermanBluefox** 2018-09-07 09:07 UTC
Labels: question
